### ISSUE TITLE
Remote debugging support.

### ISSUE THREAD

**Issue by dor666** [ovidiuvio/VSDebugPro#11]
**Describe the bug**
dumpmem not working in remote debugging.

**To Reproduce**
1. Connect two computers in network.
2. In Host computer, in Visual Studio select Debugging and set "Remote Windows Debugger".
3. Connection = Remote with no authentication
4. Remote Server Name = ip or hostname of target machine.
5. Fill Remote Command.
6. On target, install Visual studio remote debugging tools and start it. Change to "No authentication" in options.
7. Start debugging
8. Try to dump memory

Result:
```
Couldn`t dump memory to file!
Error code:-3 - NTDBG_ACCESS_DENIED.
```

Reason:
By looking at the source, I think that VSDebugPro is trying to open local process and read its memory, not the remote one.

**Comment by ovidiuvio** [comment]
Right now this is not supported. Indeed the extension will try to open local process memory.
In theory, if the remote debugger has the capability to read / write process memory, this should be possible to achieve through debugger API.

Adding this on the TODO list.

**Comment by mwerle** [comment]
+1 to this feature request.  Didn't realise this was a limitation when I found the plugin so unfortunately at present it's useless to me.  Still, great concept and looking forward to remote debugging support.
