### ISSUE TITLE
Error code:-3 - NTDBG_ACCESS_DENIED

### ISSUE THREAD

**Issue by gsorin** [ovidiuvio/VSDebugPro#18]
Hi,
VSDebug helped me a lot. 
I have switched from VS2015 to VS2017 
When I use the dumpmem command - it returns Error code:-3 - NTDBG_ACCESS_DENIED unless the  amount to dump is a few thousands bytes.
Thank you.

**Comment by ovidiuvio** [comment]
Hi,
Can you detail a bit on this ? Also are you sure that the memory range you are trying to dump is valid ?
NTDBG_ACCESS_DENIED is an error code related to memory access rights.

`

// check for valid read address
--
171 | if (!CheckReadPtr(ld_hProcess, ld_lpBaseAddress))
172 | return NTDBG_ACCESS_DENIED;
… |  
175 | if (!CheckReadPtr(ld_hProcess, ld_lpBaseAddress + (ld_nSize - 1)))
176 | return NTDBG_ACCESS_DENIED;

`

**Comment by gsorin** [comment]
Thanks.

I restarted the laptop and it's OK now.
Thanks.
Sorin

**Comment by ovidiuvio** [comment]
Ok, good to know that it is solved. I've experienced a similar problem but on an older version of VS.
I was going to suggest restarting Visual Studio as a workaround 👍
