### ISSUE TITLE
Extension will not install in Visual Studio 2019 (16.2)

### ISSUE THREAD

**Issue by alex-chung** [ovidiuvio/VSDebugPro#20]
I have Visual Studio 2019 version 16.2.0 and am unable to install the extension. I think it will only install in version 16.0.

https://devblogs.microsoft.com/visualstudio/visual-studio-extensions-and-version-ranges-demystified/

**Comment by ovidiuvio** [comment]
Should be fixed in release 3.3.0.0

**Comment by alex-chung** [comment]
Seems to be still blocking on the Microsoft.VisualStudio.Component.CoreEditor prerequisites.

**Comment by ovidiuvio** [comment]
Drafted a new release: 3.3.0.1
I've installed vs2019 16.3 Preview, and it installs and works fine for me.
Let me know if any issues.

**Comment by alex-chung** [comment]
Works now.
