### ISSUE TITLE
memdump error

### ISSUE THREAD

**Issue by sunbinjin** [ovidiuvio/VSDebugPro#28]
system:win10
vs:2017 
app:x64
error wen memdump

the memory is big than dump size.

![image](https://user-images.githubusercontent.com/14009517/103146687-0c27ee80-4788-11eb-94df-33a7f809ca51.png)

**Comment by sunbinjin** [comment]
>dumpmem -f e:\memdump.bin 0x00000205F5241080 16588800
Couldn`t dump memory to file!
Error code:-1 - NtdbgFail.
>

**Comment by ovidiuvio** [comment]
is it always happening ?. Could you provide more details ?.

**Comment by sunbinjin** [comment]
I tried again today. It's successful. Maybe it can't be repeated.

**Comment by heretique** [comment]
I'm having the same issue:
```
>dumpmem sample.raw mImageData mSize.X * mSize.Y * 4
Couldn`t dump memory to file!
Error code:-1 - NtdbgFail.
>dumpmem d:\sample.raw mImageData mSize.X * mSize.Y * 4
Couldn`t dump memory to file!
Error code:-1 - NtdbgFail.
>dumpmem -f d:\sample.raw mImageData mSize.X * mSize.Y * 4
Couldn`t dump memory to file!
Error code:-1 - NtdbgFail.
>dumpmem -f d:\Temp\sample.raw mImageData mSize.X * mSize.Y * 4
Couldn`t dump memory to file!
Error code:-1 - NtdbgFail.
>dumpmem -f d:/Temp/sample.raw mImageData mSize.X * mSize.Y * 4
Couldn`t dump memory to file!
Error code:-1 - NtdbgFail.
>dumpmem -f d:/Temp/sample.bin mImageData mSize.X * mSize.Y * 4
Couldn`t dump memory to file!
Error code:-1 - NtdbgFail.
>dumpmem -f d:/Temp/sample.bin 0x000002c9b2f30000 mSize.X * mSize.Y * 4
Couldn`t dump memory to file!
Error code:-1 - NtdbgFail.
>dumpmem -f d:/Temp/sample.raw mImageData mSize.X * mSize.Y * 4
Couldn`t dump memory to file!
Error code:-1 - NtdbgFail.
>
```
Environment: 
Win 10 Pro x64
Visual Studio 2019 16.8.6

The issue happens all the time. I've also tried running VS as an administrator but with same effect.
I've also noticed that plugin settings are lost everytime after I restart VS.

**Comment by heretique** [comment]
Apparently restarting the computer after the plugin is installed does make the dump succeed.
```
>dumpmem -f d:\Temp\sample.raw mImageData mSize.X * mSize.Y * 4
Wrote: 2240000 bytes to: <file://d:\Temp\sample.raw>.
>
```
however the settings are still lost after each restart of VS.

**Comment by ovidiuvio** [comment]
> Apparently restarting the computer after the plugin is installed does make the dump succeed.
> 
> ```
> >dumpmem -f d:\Temp\sample.raw mImageData mSize.X * mSize.Y * 4
> Wrote: 2240000 bytes to: <file://d:\Temp\sample.raw>.
> >
> ```
> 
> however the settings are still lost after each restart of VS.

Hi,

for memdump error, latest build on github releases page 3.4.0.0 changes the way memory is read / written. This should fix the occasional access denied error.
