### ISSUE TITLE
VS2022 support

### ISSUE THREAD

**Issue by Loghorn** [ovidiuvio/VSDebugPro#30]
Do you have any plan to port this to Visual Studio 2022?

**Comment by ovidiuvio** [comment]
Yes, as soon as I get some time to work on it. I have not yet had a look @VS2022 to see if there are any major changes to the VSSDK

**Comment by siilky** [comment]
Hey there, any news? =)

**Comment by SUQIGUANG** [comment]
come on, dude!!!

**Comment by sobieh** [comment]
You can check out this one:

PR:
https://github.com/ovidiuvio/VSDebugPro/pull/31
Binaries:
https://github.com/sobieh/VSDebugPro/releases

Temporary solution until author merges or makes own VS2022 release.

**Comment by ovidiuvio** [comment]
Release on main repo available here: https://github.com/ovidiuvio/VSDebugPro/releases/tag/4.0.0.0
Also available on Visual Studio gallery.

@sobieh :thank you for taking the time to port it to vs2022
