### ISSUE TITLE
can't use vsdebugpro with vs 17.12.0

### ISSUE THREAD

**Issue by yp124202453** [ovidiuvio/VSDebugPro#51]
**Describe the bug**

![image](https://github.com/user-attachments/assets/539c9638-6ae9-405e-9c43-969091205a8c)

SetSite failed for package [VSDebugProPackage]Source: 'mscorlib' Description: 异常来自 HRESULT:0x80049283
System.Runtime.InteropServices.COMException (0x80049283): 异常来自 HRESULT:0x80049283
   在 Microsoft.VisualStudio.Shell.Interop.IVsShell5.LoadPackageWithContext(Guid& packageGuid, Int32 reason, Guid& context)
   在 Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.CreateContentPane(String pszName, Int32 fDockViewOn, Int32 fDocument, String lpstrMkDoc, UInt32 eCreateWindowFlags, UInt32 dwToolWinId, Object punkView, Object punkData, IServiceProvider pServiceProvider, IVsUIHierarchy pUIHierarchy, UInt32 vsid, Int32& pfDefaultPosition, Guid& rguidCmdUI, IVsWindowFrame& ppWindowFrame)
   在 System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   在 Microsoft.VisualStudio.Shell.Package.CreateFrameForToolWindow(ToolWindowCreationResult result, Int32 id, Guid persistenceGuid)
   在 Microsoft.VisualStudio.Shell.Package.<>c__DisplayClass74_0.<CreateToolWindow>g__CreateToolWindowWorker|1()
   在 Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Type toolWindowType, Int32 id, UInt32 flags, Object context, Guid persistenceGuid)
   在 Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Type toolWindowType, Int32 id, Object context)
   在 Microsoft.VisualStudio.Shell.Package.<>c__DisplayClass84_1.<<FindToolWindow>b__1>d.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.VisualStudio.Shell.Package.<>c__DisplayClass84_0.<<FindToolWindow>b__0>d.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.VisualStudio.Shell.ToolWindowCollection.ToolWindowListener.<>c__DisplayClass1_0.<<-ctor>b__0>d.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.VisualStudio.Threading.AwaitExtensions.ExecuteContinuationSynchronouslyAwaiter`1.GetResult()
   在 Microsoft.VisualStudio.Threading.AsyncLazy`1.<>c__DisplayClass20_0.<<GetValueAsync>b__0>d.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   在 Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   在 Microsoft.VisualStudio.Threading.AsyncLazy`1.GetValue(CancellationToken cancellationToken)
   在 Microsoft.VisualStudio.Shell.Package.FindToolWindow(Type toolWindowType, Int32 id, Boolean create, ProvideToolWindowAttribute tool)
   在 VSDebugCoreLib.VSDebugContext.InitConsoleTool() 位置 D:\a\VSDebugPro\VSDebugPro\VSDebugCoreLib\VSDebugCore.cs:行号 127
   在 VSDebugCoreLib.VSDebugContext.Initialize() 位置 D:\a\VSDebugPro\VSDebugPro\VSDebugCoreLib\VSDebugCore.cs:行号 108
   在 VSDebugPro.VSDebugProPackage.Initialize()
   在 Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)

======================================================================
**To Reproduce**
1. open any solution with vs 17.12.0
2. Click menu Extension -> VsDebugPro -> About
3. a hint messagebox popup
4. See the Activitylog.xml content as up stack error

**Comment by ovidiuvio** [comment]
Thanks for reporting it @yp124202453 

Can you try this release : https://github.com/ovidiuvio/VSDebugPro/releases/tag/4.3.5.0 and let me know if it works ?

**Comment by yp124202453** [comment]
Dear ovidiuvio,    It works very well with vs 2022 17.12.0 community version.Thank you!Best wishes to you!           Yp124202453
